# Generated by Django 4.1.7 on 2023-04-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsamount',
            old_name='measurement_unit',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientsamount',
            name='name',
        ),
    ]
