# Generated by Django 4.1.7 on 2023-04-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='how_mach_time_add_to_favorite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
