# Generated by Django 4.1.7 on 2023-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingredientamount_name_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='app.tag'),
        ),
    ]
