# Generated by Django 4.1.7 on 2023-04-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipe_how_mach_time_add_to_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='how_mach_time_add_to_favorite',
            field=models.IntegerField(default=0),
        ),
    ]
