# Generated by Django 4.1.7 on 2023-04-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
