# Generated by Django 3.2 on 2023-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='app.RecipeIngredient', to='app.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
