name: FoodGram-Workflow

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Flake8 testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create python virtual env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r backend/requirements.txt
      - name: run testing Flake8
        run: |
          python -m flake8